FROM openhd/tegra_linux_sample-root-filesystem_r32.4.2_aarch64:v2

COPY .git /data/.git/
COPY bindings /data/bindings/
COPY boards /data/boards/
COPY build.py /data/
COPY fabricate.py /data/
COPY initscript /data/
COPY INSTALL.sh /data/
COPY lifepo4wered-access.c /data/
COPY lifepo4wered-access.h /data/
COPY lifepo4wered-data.c /data/
COPY lifepo4wered-data.h /data/
COPY lifepo4wered-cli.c /data/
COPY lifepo4wered-daemon.c /data/

COPY package.sh /data/

RUN apt update

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN /data/package.sh arm64 ubuntu bionic docker
